In [90]:
w = np.array(
    [
        [0, 0.4, 0.8, 0],
        [1, 0, 0, 0.7],
        [0, 0, 0, 0.3],
        [0, 0.6, 0.2, 0],
    ]
)
w_ = np.eye(4)

foo = []
for i in range(1000):
    w_ = w @ w_
    print(w_)


[[0.  0.4 0.8 0. ]
 [1.  0.  0.  0.7]
 [0.  0.  0.  0.3]
 [0.  0.6 0.2 0. ]]
[[0.4  0.   0.   0.52]
 [0.   0.82 0.94 0.  ]
 [0.   0.18 0.06 0.  ]
 [0.6  0.   0.   0.48]]
[[0.    0.472 0.424 0.   ]
 [0.82  0.    0.    0.856]
 [0.18  0.    0.    0.144]
 [0.    0.528 0.576 0.   ]]
[[0.472  0.     0.     0.4576]
 [0.     0.8416 0.8272 0.    ]
 [0.     0.1584 0.1728 0.    ]
 [0.528  0.     0.     0.5424]]
[[0.      0.46336 0.46912 0.     ]
 [0.8416  0.      0.      0.83728]
 [0.1584  0.      0.      0.16272]
 [0.      0.53664 0.53088 0.     ]]
[[0.46336  0.       0.       0.465088]
 [0.       0.839008 0.840736 0.      ]
 [0.       0.160992 0.159264 0.      ]
 [0.53664  0.       0.       0.534912]]
[[0.        0.4643968 0.4637056 0.       ]
 [0.839008  0.        0.        0.8395264]
 [0.160992  0.        0.        0.1604736]
 [0.        0.5356032 0.5362944 0.       ]]
[[0.4643968  0.         0.         0.46418944]
 [0.         0.83931904 0.83911168 0.        ]
 [0.         0.16068096 0.16088

In [91]:
import numpy as np

alpha = 0.3
beta = 0.7

w = np.array(
    [
        [1 - beta, beta, 0, alpha * beta],
        [(1 - alpha) * beta, 1 - beta, 0, 0],
        [0, 0, 1 - beta, (1 - alpha) * beta],
        [alpha * beta, 0, beta, 1 - beta],
    ]
)
w_ = np.eye(4)

foo = []
for i in range(1000):
    w_ = w @ w_
    print(w_)


[[0.3  0.7  0.   0.21]
 [0.49 0.3  0.   0.  ]
 [0.   0.   0.3  0.49]
 [0.21 0.   0.7  0.3 ]]
[[0.4771 0.42   0.147  0.126 ]
 [0.294  0.433  0.     0.1029]
 [0.1029 0.     0.433  0.294 ]
 [0.126  0.147  0.42   0.4771]]
[[0.37539  0.45997  0.1323   0.210021]
 [0.321979 0.3357   0.07203  0.09261 ]
 [0.09261  0.07203  0.3357   0.321979]
 [0.210021 0.1323   0.45997  0.37539 ]]
[[0.38210671 0.400764   0.1867047  0.2066652 ]
 [0.2805348  0.3260953  0.086436   0.13069329]
 [0.13069329 0.086436   0.3260953  0.2805348 ]
 [0.2066652  0.1867047  0.400764   0.38210671]]
[[0.35440606 0.3877039  0.20067705 0.23372727]
 [0.27139273 0.29420295 0.1174161  0.14047393]
 [0.14047393 0.1174161  0.29420295 0.27139273]
 [0.23372727 0.20067705 0.3877039  0.35440606]]
[[0.34537946 0.36439541 0.22381221 0.24287521]
 [0.25507679 0.27823579 0.13355659 0.15666854]
 [0.15666854 0.13355659 0.27823579 0.25507679]
 [0.24287521 0.22381221 0.36439541 0.34537946]]
[[0.33317138 0.35108424 0.23715631 0.25506023]
 [0.2457589

In [83]:
import numpy as np

alpha = 0.3
beta = 0.7

w = np.array(
    [
        [0.3,   0.7,    0,      0],
        [0.2,   0.3,    0,      0],
        [0,     0,      0.3,    0.5],
        [0.5,   0,      0.7,    0.5],
    ]
)
w_ = np.eye(4)

foo = []
for i in range(1000):
    w_ = w @ w_
    print(w_)


[[0.3 0.7 0.  0. ]
 [0.2 0.3 0.  0. ]
 [0.  0.  0.3 0.5]
 [0.5 0.  0.7 0.5]]
[[0.23 0.42 0.   0.  ]
 [0.12 0.23 0.   0.  ]
 [0.25 0.   0.44 0.4 ]
 [0.4  0.35 0.56 0.6 ]]
[[0.153 0.287 0.    0.   ]
 [0.082 0.153 0.    0.   ]
 [0.275 0.175 0.412 0.42 ]
 [0.49  0.385 0.588 0.58 ]]
[[0.1033 0.1932 0.     0.    ]
 [0.0552 0.1033 0.     0.    ]
 [0.3275 0.245  0.4176 0.416 ]
 [0.514  0.4585 0.5824 0.584 ]]
[[0.06963 0.13027 0.      0.     ]
 [0.03722 0.06963 0.      0.     ]
 [0.35525 0.30275 0.41648 0.4168 ]
 [0.5379  0.49735 0.58352 0.5832 ]]
[[0.046943 0.087822 0.       0.      ]
 [0.025092 0.046943 0.       0.      ]
 [0.375525 0.3395   0.416704 0.41664 ]
 [0.55244  0.525735 0.583296 0.58336 ]]
[[0.0316473 0.0592067 0.        0.       ]
 [0.0169162 0.0316473 0.        0.       ]
 [0.3888775 0.3647175 0.4166592 0.416672 ]
 [0.562559  0.5444285 0.5833408 0.583328 ]]
[[0.02133553 0.03991512 0.         0.        ]
 [0.01140432 0.02133553 0.         0.        ]
 [0.39794275 0.3816295  0.41666

In [81]:
w = np.array(
    [
        [0, 0, 1],
        [1, 0, 0],
        [0, 1, 0],
    ]
)
w_ = np.eye(3)

foo = []
for i in range(1000):
    w_ = w @ w_
    print(w_)


[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[

In [76]:
import numpy as np

alpha = 0.3
beta = 0.7

w = np.array(
    [
        [1 - alpha, alpha * (1 - beta), 0, alpha * beta],
        [alpha * (1 - beta), 1 - alpha, 0, 0],
        [0, 0, 1 - alpha, alpha * (1 - beta)],
        [alpha * beta, 0, alpha * (1 - beta), 1 - alpha],
    ]
)
w_ = np.eye(4)

foo = []
for i in range(1000):
    w_ = w @ w_
    print(w_) 
    foo.append(w_[0, 0])



[[0.7  0.09 0.   0.21]
 [0.09 0.7  0.   0.  ]
 [0.   0.   0.7  0.09]
 [0.21 0.   0.09 0.7 ]]
[[0.5422 0.126  0.0189 0.294 ]
 [0.126  0.4981 0.     0.0189]
 [0.0189 0.     0.4981 0.126 ]
 [0.294  0.0189 0.126  0.5422]]
[[0.45262  0.136998 0.03969  0.321363]
 [0.136998 0.36001  0.001701 0.03969 ]
 [0.03969  0.001701 0.36001  0.136998]
 [0.321363 0.03969  0.136998 0.45262 ]]
[[0.39665005 0.1366344  0.05670567 0.3235764 ]
 [0.1366344  0.26433682 0.0047628  0.05670567]
 [0.05670567 0.0047628  0.26433682 0.1366344 ]
 [0.3235764  0.05670567 0.1366344  0.39665005]]
[[0.35790317 0.13134258 0.06881585 0.3149035 ]
 [0.13134258 0.19733287 0.00843747 0.06881585]
 [0.06881584 0.00843747 0.19733287 0.13134258]
 [0.3149035  0.06881585 0.13134258 0.35790317]]
[[0.32848279 0.12415109 0.07651241 0.30178554]
 [0.12415109 0.14995384 0.01209966 0.07651241]
 [0.07651241 0.01209966 0.14995384 0.12415109]
 [0.30178554 0.07651241 0.12415109 0.32848279]]
[[0.30448652 0.11646922 0.08071938 0.28711738]
 [0.1164692

In [ ]:
np.random.randint(0, 10, 5)

In [72]:
import numpy as np


w = np.array(
    [
        [0, 0.2, 0],
        [1, 0, 1],
        [0, 0.8, 0],
    ]
)
x = np.array([1/3, 1/3, 1/3])

for i in range(100):
    x = w @ x
    print(x)
    print()


[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.53333333]

[0.06666667 0.66666667 0.26666667]

[0.13333333 0.33333333 0.533

In [44]:
np.random.randint(0, 10, 5)

array([4, 8, 3, 0, 3])

In [69]:
import numpy as np

w = np.random.randint(0, 10, (5,5)) 
w = w / w.sum(axis=1)[:, np.newaxis]

x = np.random.randint(0, 10, 5)
x = x / x.sum()
# foo, foo.sum(axis=1)

for i in range(100):
    x = w @ x
    print(x)

[0.20234114 0.25889328 0.12374582 0.22826087 0.17236025]
[0.19493968 0.20893681 0.17648029 0.20708949 0.17898522]
[0.19375037 0.19598725 0.18589058 0.1969471  0.18949279]
[0.19273954 0.19360758 0.19020233 0.19316603 0.19133919]
[0.19223417 0.19249156 0.19160767 0.19246623 0.19176102]
[0.1921321  0.19218633 0.19191721 0.19219858 0.19200599]
[0.192096   0.19211624 0.19203067 0.19210872 0.19205738]
[0.19208297 0.19208905 0.19206564 0.19208848 0.19207081]
[0.19207993 0.19208142 0.19207437 0.19208152 0.19207657]
[0.19207895 0.19207946 0.19207728 0.19207932 0.19207793]
[0.19207862 0.19207878 0.19207816 0.19207876 0.19207831]
[0.19207854 0.19207858 0.1920784  0.19207858 0.19207845]
[0.19207851 0.19207853 0.19207847 0.19207853 0.19207849]
[0.19207851 0.19207851 0.19207849 0.19207851 0.1920785 ]
[0.1920785  0.19207851 0.1920785  0.19207851 0.1920785 ]
[0.1920785 0.1920785 0.1920785 0.1920785 0.1920785]
[0.1920785 0.1920785 0.1920785 0.1920785 0.1920785]
[0.1920785 0.1920785 0.1920785 0.1920785 

In [49]:
x

array([0.16974249, 0.16974249, 0.16974249, 0.16974249, 0.16974249])

In [41]:
w

array([[0.        , 0.38888889, 0.38888889, 0.22222222, 0.        ],
       [0.04      , 0.32      , 0.08      , 0.28      , 0.28      ],
       [0.17241379, 0.13793103, 0.17241379, 0.20689655, 0.31034483],
       [0.42857143, 0.0952381 , 0.23809524, 0.04761905, 0.19047619],
       [0.38888889, 0.05555556, 0.33333333, 0.11111111, 0.11111111]])

In [34]:
foo.sum(axis=1)[:, np.newaxis]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
import numpy as np


w = np.array(
    [
        [3 / 4, 1 / 4, 0, 0, 0],
        [3 / 4, 0, 1 / 4, 0, 0],
        [3 / 4, 0, 0, 1 / 4, 0],
        [3 / 4, 0, 0, 0, 1 / 4],
        [1, 0, 0, 0, 0],
    ]
)
w_ = np.eye(5)

for i in range(100):
    w_ = np.dot(w, w_)
    print(w_)


In [ ]:
w.shape, x.shape